disabled_rules:
  - unused_closure_parameter
  - unused_setter_value
  - cyclomatic_complexity
opt_in_rules:
  - let_var_whitespace
  - operator_usage_whitespace
analyzer_rules:
  - unused_declaration
  - unused_import
included:
  - ./
  - ../Sources
excluded:
  - Pods
identifier_name:
  allowed_symbols: "_"
  min_length: 1
type_name:
  allowed_symbols: "_"
trailing_whitespace:
  severity: error
  ignores_empty_lines: true
line_length:
  warning: 1800
  error: 1800
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
  ignores_comments: true
file_length:
  warning: 500
  error: 500
  ignore_comment_only_lines: true
function_body_length:
  warning: 200
  error: 200
nesting:
  type_level:
    warning: 3
    error: 3
function_parameter_count:
  warning: 5
  error: 5
unused_optional_binding:
  severity: error
  ignore_optional_try: true
private_over_fileprivate:
  severity: error
colon:
  severity: error
vertical_whitespace:
  severity: error
trailing_comma:
  severity: error
opening_brace:
  severity: error
unused_declaration:
  severity: error
  include_public_and_open: true
unused_import:
  severity: error
operator_usage_whitespace:
  severity: error
comma: error
redundant_void_return: error
trailing_semicolon: error
control_statement: error
todo: error
unneeded_break_in_switch: error
redundant_discardable_let: error
let_var_whitespace: error
operator_whitespace: error
trailing_newline: error
empty_parentheses_with_trailing_closure: error
legacy_cggeometry_functions: error
legacy_constant: error
legacy_constructor: error
legacy_nsgeometry_functions: error
legacy_random: error
unneeded_synthesized_initializer: error
